version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"

    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
